# Generated by Django 5.0.7 on 2024-08-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=26, verbose_name='Category name')),
                ('name_ru', models.CharField(db_index=True, max_length=26, verbose_name='Category name ru')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Position')),
                ('name', models.CharField(db_index=True, max_length=35, verbose_name='Name')),
                ('name_ru', models.CharField(db_index=True, max_length=35, verbose_name='Name ru')),
                ('description', models.CharField(db_index=True, max_length=41, verbose_name='Description')),
                ('description_ru', models.CharField(db_index=True, max_length=41, verbose_name='Description ru')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('preview_image', models.ImageField(upload_to='posts/previews/')),
                ('small_preview', models.BooleanField(default=False, verbose_name='Small preview')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='+', to='core.post'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=22, verbose_name='Section name')),
                ('categories', models.ManyToManyField(to='core.category')),
            ],
        ),
    ]
