# Generated by Django 5.0.7 on 2024-08-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('preview_image', models.ImageField(upload_to='posts/previews/')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='+', to='core.post'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Section name')),
                ('categories', models.ManyToManyField(to='core.category')),
            ],
        ),
    ]
