# Generated by Django 5.0.7 on 2024-08-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=26, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(db_index=True, max_length=41, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, max_length=35, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, max_length=22, verbose_name='Section name'),
        ),
    ]
