# Generated by Django 5.0.7 on 2024-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Position'),
        ),
    ]
