# Generated by Django 5.0.7 on 2024-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Position'),
        ),
    ]
