# Generated by Django 5.0.7 on 2024-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, unique=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='posts/previews/'),
        ),
    ]
