# Generated by Django 5.0.7 on 2024-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_position_alter_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=41, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Position'),
        ),
    ]
